#!/usr/bin/env python3
"""Write the bench startup sequence, ``sequences/bench_startup.seq``.

The bench file is ``sequences/startup.seq`` with the commands a bench board
must not run removed, and nothing else changed. The output is two fixed header
lines, then every source line in order, byte for byte, one ``\\n`` after each,
except:

1. a command line whose command is ``ReferenceDeployment.antennaDeployer.DEPLOY``,
   ``ReferenceDeployment.modeManager.EXIT_SAFE_MODE`` or
   ``ReferenceDeployment.detumbleManager.SET_MODE`` (any argument);
2. a command line whose command is ``ReferenceDeployment.lora.TRANSMIT`` and
   whose first argument is ``ENABLED`` (``TRANSMIT, DISABLED`` is kept);
3. a comment line (first non-blank character ``;``) immediately before a line
   dropped by rule 1 or 2;
4. every blank line after the last non-blank kept line, so the file ends in
   exactly one ``\\n`` (the ``end-of-file-fixer`` hook requires it). Blank
   lines inside the sequence are kept.

A command line starts with a time tag (``R00:00:00`` or
``A2026-001T00:00:00``); its command is the next run of characters up to the
first whitespace or comma; its first argument is the first whitespace-delimited
token of the text after the command, up to the first ``;``, with leading commas
and whitespace removed.

Modes: default writes ``--output`` and prints ``wrote <path>``; ``--stdout``
prints the text instead; ``--check`` writes nothing and exits 0 (silently) only
when ``--output`` equals the regenerated text byte for byte, else 1 with
``<basename>: stale`` or ``<basename>: missing``. Exit 2 when ``--source``
cannot be read: nothing on stdout, one stderr line ``error: <what> (<path>)``.

Usage: ``fprime-venv/bin/python3 scripts/make_bench_sequence.py`` from the repo
root (``make bench-sequence``). Standard library only.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = "sequences/startup.seq"
DEFAULT_OUTPUT = "sequences/bench_startup.seq"

HEADER = (
    b"; GENERATED by scripts/make_bench_sequence.py from sequences/startup.seq"
    b" - do not edit; regenerate: make bench-sequence\n"
    b"; Bench variant: no antennaDeployer.DEPLOY, no lora.TRANSMIT ENABLED,"
    b" no modeManager.EXIT_SAFE_MODE, no detumbleManager.SET_MODE."
    b" Select it with startupManager.STARTUP_SEQUENCE_FILE.\n"
)

TIME_TAG_RE = re.compile(rb"R\d\d:\d\d:\d\d|A\d\d\d\d-\d\d\dT\d\d:\d\d:\d\d")
COMMAND_RE = re.compile(rb"[^\s,]+")
ALWAYS_DROPPED = {
    b"ReferenceDeployment.antennaDeployer.DEPLOY",
    b"ReferenceDeployment.modeManager.EXIT_SAFE_MODE",
    b"ReferenceDeployment.detumbleManager.SET_MODE",
}
TRANSMIT = b"ReferenceDeployment.lora.TRANSMIT"


class InputError(Exception):
    """An input the script cannot use (exit 2)."""

    def __init__(self, what: str, path: object):
        """Remember what was wrong and which path it concerns."""
        super().__init__(what)
        self.what = what
        self.path = path

    def message(self) -> str:
        """The one stderr line."""
        return f"error: {self.what} ({self.path})"


def command_and_argument(line: bytes) -> tuple[bytes, bytes] | None:
    """``(command, first argument)`` of a command line, or ``None`` for any other line."""
    parts = line.split(None, 1)
    if not parts or not TIME_TAG_RE.fullmatch(parts[0]) or len(parts) == 1:
        return None
    match = COMMAND_RE.match(parts[1])
    if match is None:
        return None
    rest = parts[1][match.end() :].split(b";", 1)[0]
    tokens = re.sub(rb"^[,\s]+", b"", rest).split()
    return match.group(0), tokens[0] if tokens else b""


def is_dropped(line: bytes) -> bool:
    """Rules 1 and 2: a hazard command line."""
    parsed = command_and_argument(line)
    if parsed is None:
        return False
    command, argument = parsed
    return command in ALWAYS_DROPPED or (command == TRANSMIT and argument == b"ENABLED")


def generate(source: bytes) -> bytes:
    """The bench sequence text for the flight sequence ``source``."""
    lines = source.split(b"\n")
    if lines and lines[-1] == b"":
        lines.pop()
    dropped = [is_dropped(line) for line in lines]
    kept = []
    for i, line in enumerate(lines):
        if dropped[i]:
            continue
        if line.lstrip().startswith(b";") and i + 1 < len(lines) and dropped[i + 1]:
            continue
        kept.append(line)
    while kept and not kept[-1].strip():
        kept.pop()
    return HEADER + b"".join(line + b"\n" for line in kept)


def read_source(path: Path) -> bytes:
    """Read ``--source`` or raise ``InputError``."""
    if not path.is_file():
        raise InputError("--source is missing", path)
    try:
        return path.read_bytes()
    except OSError as error:
        raise InputError(f"--source cannot be read: {error.strerror}", path) from None


def resolve(given: str | None, default: str) -> tuple[Path, str]:
    """The path to open and the string to print for ``--source``/``--output``."""
    if given is None:
        return ROOT / default, default
    return Path(given), given


def parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse the command line."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--source", default=None, help=f"default {DEFAULT_SOURCE}")
    parser.add_argument("--output", default=None, help=f"default {DEFAULT_OUTPUT}")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--stdout", action="store_true")
    mode.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Write, print or check the bench sequence and return the exit status."""
    args = parse_args(argv)
    source, _ = resolve(args.source, DEFAULT_SOURCE)
    output, shown = resolve(args.output, DEFAULT_OUTPUT)
    try:
        text = generate(read_source(source))
    except InputError as error:
        print(error.message(), file=sys.stderr)
        return 2
    if args.stdout:
        sys.stdout.flush()
        sys.stdout.buffer.write(text)
        sys.stdout.buffer.flush()
        return 0
    if args.check:
        if not output.is_file():
            print(f"{output.name}: missing")
            return 1
        if output.read_bytes() != text:
            print(f"{output.name}: stale")
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(text)
    print(f"wrote {shown}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
